---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(badger)
```

# Outcomes of Coronary Artery bypass Grafting in Heart failure with a mid-range Ejection Fraction.

`r badge_doi("https://doi.org/10.1016/j.jtcvs.2021.01.035", "blue")` 

`r badge_custom("Louis Stokes Cleveland VA Medical Center", "Cleveland VA CV Research Group","yellow")`




*Salil V Deo MD^1,2^, Varun Sundaram MD^2,3^, Jayakumar Sahadevan MD^2,3^, Padmini Selvaganesan PhD^3^,Srikrishna Madan Mohan MD^2^, Joseph Rubelowsky MD^1^, Richard Josephson MD^2,4^, Yakov Elgudin MD^1^,Ahmet Kilic MD^5^, Brian Cmolik MD^1^*








## Affiliations:

1 – Surgical Services, Louis Stokes Cleveland VA Medical Center, Cleveland Ohio

2 – Cleveland VA CV Research Group, Cleveland Ohio

3 – Department of Cardiovascular Medicine, Louis Stokes Cleveland VA Medical Center, Cleveland Ohio

4 – Department of Cardiovascular Medicine, Harrington Heart and Vascular Institute, Cleveland Medical Center, Cleveland Ohio

5 – Department of Cardiac Surgery, John Hopkins School of Medicine, Baltimore, Maryland

*-both authors have contributed equally to this study

This public repository contains the code for the paper published in the Journal of Thoracic and Cardiovascular Surgery.



### Address for Correspondence:

#### Salil V Deo MD

Surgical Services,

NorthEast Ohio VA Healthcare System

Associate Professor of Surgery,

Case School of Medicine,

Case Western Reserve University

Cleveland, Ohio 44106

Email: svd14@case.edu

This repository contains code for the manuscript. It does not contain any PHI or HIPAA protected information.


